export const LOGIN_TOKEN = "LOGIN_TOKEN";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_LOADING = "LOGIN_LOADING";
export const RESET_PASSWORD = "RESET_PASSWORD";
export const RESET_PASSWORD_ERROR = "RESET_PASSWORD_ERROR";
export const RESET_NEW_PASSWORD = "RESET_NEW_PASSWORD";
export const RESET_NEW_PASSWORD_ERROR = "RESET_NEW_PASSWORD_ERROR";
export const OTP_VERIFY_EMAIL = "OTP_VERIFY_EMAIL";
export const OTP_VERIFY_EMAIL_ERROR = "OTP_VERIFY_EMAIL_ERROR";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const CHANGE_PASSWORD_ERROR = "CHANGE_PASSWORD_ERROR";

export const CREATING_NODE = "CREATING_NODE";
export const UPDATING_NODE = "UPDATING_NODE";
export const UPDATE_NODE_STATUS = "UPDATE_NODE_STATUS";
export const UPDATE_NODE_REPORT = "UPDATE_NODE_REPORT";
export const CREATE_NODE = "CREATE_NODE";
export const UPDATE_NODE = "UPDATE_NODE";
export const INSTALL_NODE = "INSTALL_NODE";
export const UNINSTALL_NODE = "UNINSTALL_NODE";
export const RESTART_NODE = "RESTART_NODE";
export const GET_NODES = "GET_NODES";
export const DELETE_NODES = "DELETE_NODES";
export const GET_VIEW = "GET_VIEW";
export const UPDATE_VIEW = "UPDATE_VIEW";
export const GET_META = "GET_META";
export const SINGLESHOT = "SINGLESHOT";

export const GET_SIMULATION_LIST = "GET_SIMULATION_LIST";
export const CREATE_SIMULATION_VIEW = "CREATE_SIMULATION_VIEW";
export const DELETE_SIMULATION_VIEW = "DELETE_SIMULATION_VIEW";
export const CLONE_SIMULATION_VIEW = "CLONE_SIMULATION_VIEW";
export const CREATING_SIMULATION_NODE = "CREATING_SIMULATION_NODE";
export const CREATE_SIMULATION_NODE = "CREATE_SIMULATION_NODE";
export const UPDATE_SIMULATION_PROGRESS = "UPDATE_SIMULATION_PROGRESS";
export const CAPTURE_LIST = "CAPTURE_LIST";
export const GET_SIMULATION_NODES = "GET_SIMULATION_NODES";
export const DELETE_SIMULATION_NODES = "DELETE_SIMULATION_NODES";
export const SIMULATION_LOADING = "SIMULATION_LOADING";
export const GET_SIMULATION_VIEW = "GET_SIMULATION_VIEW";
export const UPDATE_SIMULATION_VIEW = "UPDATE_SIMULATION_VIEW";
export const RESET_SIMULATION_CONFIGURATION = "RESET_SIMULATION_CONFIGURATION";
export const CONFIG_SIMULATION_BUTTON = "CONFIG_SIMULATION_BUTTON";
export const GET_SIMULATION_EVENTS = "GET_SIMULATION_EVENTS";
export const RESET_CONFIGURATION = "RESET_CONFIGURATION";
export const UPDATE_CONFIG_STORE = "UPDATE_CONFIG_STORE";
export const RESET_FLAGS = "RESET_FLAGS";
export const CONFIG_BUTTON = "CONFIG_BUTTON";
export const GET_EVENTS = "GET_EVENTS";
export const UPDATE_EVENTS = "UPDATE_EVENTS";
export const GET_VERSIONS = "GET_VERSIONS";
export const DELETE_EDGE = "DELETE_EDGE";

export const SUBSCRIBER_LOADING = "SUBSCRIBER_LOADING";

export const CREATING_SUBSCRIBER_NODE = "CREATING_SUBSCRIBER_NODE";
export const CREATE_SUBSCRIBER_NODE = "CREATE_SUBSCRIBER_NODE";
export const UPDATE_SUBSCRIBER_NODE = "UPDATE_SUBSCRIBER_NODE";
export const GET_SUBSCRIBER_NODES = "GET_SUBSCRIBER_NODES";
export const DELETE_SUBSCRIBER_NODES = "DELETE_SUBSCRIBER_NODES";
export const GET_SUBSCRIBER_LIST = "GET_SUBSCRIBER_LIST";
export const GET_SUBSCRIBER_VIEW = "GET_SUBSCRIBER_VIEW";
export const CREATE_SUBSCRIBER_VIEW = "CREATE_SUBSCRIBER_VIEW";
export const DELETE_SUBSCRIBER_VIEW = "DELETE_SUBSCRIBER_VIEW";
export const UPDATE_SUBSCRIBER_VIEW = "UPDATE_SUBSCRIBER_VIEW";
export const RESET_SUBSCRIBER_CONFIGURATION = "RESET_SUBSCRIBER_CONFIGURATION";
export const CONFIG_SUBSCRIBER_BUTTON = "CONFIG_SUBSCRIBER_BUTTON";

export const GET_SYSTEM_INFO = "GET_SYSTEM_INFO";
export const GET_STATS_INFO = "GET_STATS_INFO";
export const GET_NETWORK_INFO = "GET_NETWORK_INFO";

export const GET_SETUP_LIST = "GET_SETUP_LIST";
export const CREATE_SETUP = "CREATE_SETUP";
export const CLONE_SETUP = "CLONE_SETUP";
export const DELETE_SETUP = "DELETE_SETUP";
export const UPDATE_SETUP = "UPDATE_SETUP";
export const UPDATE_SETUP_STATUS = "UPDATE_SETUP_STATUS";
export const INSTALL_SETUP = "INSTALL_SETUP";
export const UNINSTALL_SETUP = "UNINSTALL_SETUP";
export const VERSION_CHANGE_SETUP = "VERSION_CHANGE_SETUP";
export const AGENT_LIST = "AGENT_LIST";
export const FETCH_AGENT_STATS = "FETCH_AGENT_STATS";
export const AGENT_PING = "AGENT_PING";

export const START_SIMULATION = "START_SIMULATION";
export const STOP_SIMULATION = "STOP_SIMULATION";
export const GET_SIM_INSTANCE = "GET_SIM_INSTANCE";

export const V1_GET_SETUP_DATA = "V1_GET_SETUP_DATA";
export const V1_SAVE_SETUP = "V1_SAVE_SETUP";
export const V1_CONFIG_CHANGE = "V1_CONFIG_CHANGE";
export const TOGGLE_SNACKBAR_CLOSE = "TOGGLE_SNACKBAR_CLOSE";

export const GET_EXECUTE_SETUP_LIST = "GET_EXECUTE_SETUP_LIST";
export const SETUP_SCRIPT_START = "SETUP_SCRIPT_START";
export const SETUP_SCRIPT_STOP = "SETUP_SCRIPT_STOP";
export const EXECUTE_COMMAND = "EXECUTE_COMMAND";
export const SETUP_LIST_CAPTURE = "SETUP_LIST_CAPTURE";
export const SETUP_START_CAPTURE = "SETUP_START_CAPTURE";
export const SETUP_STOP_CAPTURE = "SETUP_STOP_CAPTURE";
export const SETUP_DELETE_CAPTURE = "SETUP_DELETE_CAPTURE";
export const CONSOLE_LOG = "CONSOLE_LOG";
export const CONSOLE_LOG_RESET = "CONSOLE_LOG_RESET";
export const EXEC_RESET = "EXEC_RESET";
export const EXEC_STATUS = "EXEC_STATUS";
export const SCRIPT_EXEC_LOGS = "FETCH_SCRIPT_EXEC_LOGS";
export const APPEND_SCRIPT_EXEC_LOG = "APPEND_SCRIPT_EXEC_LOG";
export const FETCH_APPLICATION_STATS = "FETCH_APPLICATION_STATS";
export const FETCH_DOWNLOADS = "FETCH_DOWNLOADS";
export const FETCH_SETTINGS = "FETCH_SETTINGS";
export const SAVE_SETTINGS = "SAVE_SETTINGS";

export const FETCH_KEYS = "FETCH_KEYS";
export const FETCH_STATS_DATA = "FETCH_STATS_DATA";
export const FETCH_EVENT_LOGS = "FETCH_EVENT_LOGS";

export const GET_PROC_TREE = "GET_PROC_TREE";

export const UE_DISTRIBUTIONS = "UE_DISTRIBUTIONS";
export const UPDATE_SUBSCRIBER_PROGRESS = "UPDATE_SUBSCRIBER_PROGRESS";
